// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpYf3S8f3erkpuA6W_zO7FjpU4YHFZgUs',
    appId: '1:848880563349:web:3064d8f784114f064bd79c',
    messagingSenderId: '848880563349',
    projectId: 'task-management-apps-5b838',
    authDomain: 'task-management-apps-5b838.firebaseapp.com',
    storageBucket: 'task-management-apps-5b838.appspot.com',
    measurementId: 'G-KSM0L125MF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl5A3xQ5j-smpYX_z8QLccm81dy41g6_w',
    appId: '1:848880563349:android:7e4599e2a39188434bd79c',
    messagingSenderId: '848880563349',
    projectId: 'task-management-apps-5b838',
    storageBucket: 'task-management-apps-5b838.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgZFpDngQvlwsewYNDMk1esl2oHx-yQ7M',
    appId: '1:848880563349:ios:a945e78cedf8b2644bd79c',
    messagingSenderId: '848880563349',
    projectId: 'task-management-apps-5b838',
    storageBucket: 'task-management-apps-5b838.appspot.com',
    androidClientId: '848880563349-mf1e222ur1fk756e4beht6ker91i9ch8.apps.googleusercontent.com',
    iosClientId: '848880563349-1arg010pjb518a54enunrtu96s3fkkos.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZFpDngQvlwsewYNDMk1esl2oHx-yQ7M',
    appId: '1:848880563349:ios:a945e78cedf8b2644bd79c',
    messagingSenderId: '848880563349',
    projectId: 'task-management-apps-5b838',
    storageBucket: 'task-management-apps-5b838.appspot.com',
    androidClientId: '848880563349-mf1e222ur1fk756e4beht6ker91i9ch8.apps.googleusercontent.com',
    iosClientId: '848880563349-1arg010pjb518a54enunrtu96s3fkkos.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApp',
  );
}
